version: "3.9"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: example
      POSTGRES_USER: example
      # POSTGRES_PASSWORD is intentionally missing